### ISSUE TITLE
Update server infos

### ISSUE THREAD

**Issue by sebastienservouze** [TheHiddenCodders/KangarooFighter#7]
Choose when to update server infos : 
- on any client connection update for all of them ?
- on any client disconnection update for all of them ?
- on match making entry ?

**Comment by Kurond** [comment]
I want to change the way serverInfoPacket are used. Currently they are created by the client, sent to the server which fill it in and sent back to the client. But with this method, the client need to request the server to update the infos.

So after the changes, the server will create the serverInfoPacket to all clients if and only if there is some changes. For example if a new client logged in, the infos are updated and sent to all clients.
