### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by Kurond** [TheHiddenCodders/KangarooFighter#9]
Make research to manage progress bar with scene2d ui.

**Comment by sebastienservouze** [comment]
Still a little bug due to float / int values that draw the hitbar 2 pixels right of where it should be !

**Comment by Kurond** [comment]
I think it come from the draw method of ProgressBar (line 79). It's here the yellow bar is drawn, but its X position is function of the bar size. Indeed : this.getX() + getProgressWidth(...). 

So to avoid this, the X position of the yellow bar doesn't depend on getProgressWidth(). In fact this position depend on the bar position and the size of the black line.

**Comment by sebastienservouze** [comment]
Done, what due to sprite sheet
